<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><LangVersion>latest</LangVersion><GamePath Condition="'$(GamePath)' == ''">D:\Steam\steamapps\common\PEAK</GamePath></PropertyGroup>
  <ItemGroup>
    <Reference Include="$(GamePath)/BepInEx/core/BepInEx.dll" />
    <Reference Include="$(GamePath)/BepInEx/core/0Harmony.dll" />
    <Reference Include="$(GamePath)/PEAK_Data/Managed/UnityEngine.dll" />
    <Reference Include="$(GamePath)/PEAK_Data/Managed/UnityEngine.CoreModule.dll" />
    <Reference Include="$(GamePath)/PEAK_Data/Managed/UnityEngine.ParticleSystemModule.dll" />
    <Reference Include="$(GamePath)/PEAK_Data/Managed/UnityEngine.PhysicsModule.dll" />
  </ItemGroup>
</Project>
