<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>13dda</AssemblyName>
    <RootNamespace>dda</RootNamespace>
    <Version>1.5.19</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=/src/PeakAscentsContinued</PathMap>
    <GamePath Condition="'$(GamePath)' == ''">D:\Steam\steamapps\common\PEAK</GamePath>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src/**/*.cs" />
    <EmbeddedResource Include="src/Resources/NativeAlpineSnow.bundle" LogicalName="dda.NativeAlpineSnow.bundle" />
    <Reference Include="$(GamePath)/PEAK_Data/Managed/*.dll" Exclude="$(GamePath)/PEAK_Data/Managed/mscorlib.dll;$(GamePath)/PEAK_Data/Managed/netstandard.dll;$(GamePath)/PEAK_Data/Managed/System*.dll;$(GamePath)/PEAK_Data/Managed/Microsoft*.dll;$(GamePath)/PEAK_Data/Managed/Mono*.dll;$(GamePath)/PEAK_Data/Managed/Assembly-CSharp.dll">
      <Private>false</Private>
    </Reference>
    <Reference Include="$(GamePath)/BepInEx/core/BepInEx.dll"><Private>false</Private></Reference>
    <Reference Include="$(GamePath)/BepInEx/core/0Harmony.dll"><Private>false</Private></Reference>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" PrivateAssets="all" />
    <Reference Include="$(GamePath)/PEAK_Data/Managed/Assembly-CSharp.dll" Publicize="true"><Private>false</Private></Reference>
  </ItemGroup>
</Project>
